### ISSUE TITLE
IOError: [Errno 5] Input/output error IN DOCKER

### ISSUE THREAD

**Issue by antoniphuoc** [pi-node/instructions#253]
I'm still seeing my problem on docker ,

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit

    self.flush()

  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush

    self.stream.flush()

IOError: [Errno 5] Input/output error

My computer is running at node and running consensus container, Has anyone had this problem before, I need help
![new](https://user-images.githubusercontent.com/78890362/161882718-d81e2429-43af-43a6-b5c4-abb6399349d0.png)
![neww](https://user-images.githubusercontent.com/78890362/161882722-225fb748-b49b-4453-8373-690f7a4a390a.png)

**Comment by ihatejam** [comment]
I'd guess this is a permissions thing - where python is trying to output/write something where it does not have permissions to write -- chances are you missed out on a prompt to grant permissions when you were installing Docker or the node app or something of that nature. 
Since the majority of us have this running just fine, I would urge you to completely uninstall the pi node and docker - and start it all from scratch. 

Also, I would switch off the API service to save a small bit of disk space and processing -- unless you're an app developer planning on testing local access to the blockchain.

**Comment by MartinRe63** [comment]
@ihatejam  - The API service (Application Programming Interface) will be used by PI Application and other Application to access the block chain (later also Exchanges will use this API). If Pioneers have Storage available they should enable the API service. It has nothing to you with being an APP developer. If you want to use the PI Network API one must not be a Pioneer hosting a node. Thx.

**Comment by KelvinSolar** [comment]
I have the same problem like that, how can u solve it? Thanks!

**Comment by knrgmodz** [comment]
I removed block chain data in pi node and started to go as normal, also be sure you have plenty of disk space on c:/
