### ISSUE TITLE
Pi Node not updating

### ISSUE THREAD

**Issue by miguelkv** [pi-node/instructions#263]
I am trying to run the node on my desktop, but it doesn't seem to be working properly.
I tested it and I can access it from all locations (same computer, same network, and internet).
But for some weird reason, it doesn't want to download the blocks:
![image](https://user-images.githubusercontent.com/5353533/164703215-be344671-896a-4eb9-b432-e4ce511c6ca7.png)
It's in this state for a few days, and nothing that I do seems to have any effect.

What am I doing wrong?
What should I do to fix it?

Thanks.

**Comment by adwards74** [comment]
Actions you can take.
first. Execute Remove all blockchain data
Second. Update Docker to the latest version.
third. latest windows update

And always use genuine Windows.

**Comment by miguelkv** [comment]
1. Clicked on that button, let me check what happens... It seems that there are a few things to reconfigure.
2. Docker is up to date: 
![image](https://user-images.githubusercontent.com/5353533/164894059-ed99ac37-ca7d-4429-b445-c12a6a096301.png)

3. Original Windows 11 and with all updates.

**Comment by ChrisAB** [comment]
What are your PC stats? (CPU, RAM, Do you have a HDD or SSD?)

**Comment by miguelkv** [comment]
i7, 11th gen, 32GB, SSD for SO, HDD for data.
So far, it doesn't seem to be working properly... I will try to uninstall everything and then reinstall it.

**Comment by miguelkv** [comment]
Update: uninstalling both Pi app and Docker, then reinstalling them, fixed the issue.

**Comment by adwards74** [comment]
Good job! Enjoy mining!

**Comment by AaryanKapoor22** [comment]
bump i am having this issue and tried every single step
[2022-05-19 17:40:55.986] [error] Error: Error: Cannot find channel "latest.yml" update info: HttpError: 404 Not Found
"method: GET url: https://downloads.minepi.com/node-manifests/latest.yml?noCache=1g3e8phca\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "nginx/1.14.0 (Ubuntu)",
  "date": "Thu, 19 May 2022 13:40:55 GMT",
  "content-type": "text/html",
  "transfer-encoding": "chunked",
  "connection": "keep-alive",
  "content-encoding": "gzip"
}
    at createHttpError (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:86:16)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:475:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:130:23)
    at newError (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at GenericProvider.getLatestVersion (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:27:17)
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:355:13)
    at NsisUpdater.doCheckForUpdates (C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:372:20)
[2022-05-19 17:40:58.628] [error] run: stats: drive.info(): err: Error: disk name invalid and / not found
    at C:\Users\Rajiv Kapoor\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\node-os-utils\lib\drive.js:62:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2022-05-19 17:40:58.703] [info] horizonStatusCommand: start
[2022-05-19 17:40:58.878] [error] dockerFlavorSync: command error:  Error: Command failed: docker-machine env default
