### ISSUE TITLE
Pinging is not working

### ISSUE THREAD

**Issue by jaydeepvagadiya** [pi-node/instructions#298]
Hello Guys,
Please help me on this error..
"Pinging your computer " is not working...

[2022-10-14 10:16:26.859] [info] run: heartbeat: OK
[2022-10-14 10:16:26.939] [info] run: heartbeat: update-check: started: local-docker-image:  pinetwork/pi-node-docker:latest  new-docker-image: pinetwork/pi-node-docker:latest
[2022-10-14 10:16:26.940] [info] run: heartbeat: update-check: done: either already up to date, or not allowed to update, or docker daemon / container is not running
[2022-10-14 10:16:27.028] [error] run: stats: drive.info(): err: Error: disk name invalid and / not found
    at C:\Users\Jaydeep Vagadiya\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\node-os-utils\lib\drive.js:62:17
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2022-10-14 10:16:27.068] [info] [IPC] dockerDaemonStatus
[2022-10-14 10:16:27.080] [info] [IPC] dockerDaemonInstallationCheck
[2022-10-14 10:16:28.511] [info] dockerDaemonInstallationCheckCommand: version 20.10.12
![Capture](https://user-images.githubusercontent.com/31248548/195765707-b21d68e1-6982-43d8-8062-19cb6ce23f44.PNG)

**Comment by jaydeepvagadiya** [comment]
New Error:

[2022-10-14 10:34:28.705] [info] run: heartbeat: OK
[2022-10-14 10:34:28.708] [info] run: heartbeat: update-check: started: local-docker-image:  pinetwork/pi-node-docker:latest  new-docker-image: pinetwork/pi-node-docker:latest
[2022-10-14 10:34:28.709] [info] run: heartbeat: update-check: done: either already up to date, or not allowed to update, or docker daemon / container is not running
[2022-10-14 10:34:28.876] [error] run: stats: drive.info(): err: Error: disk name invalid and / not found
    at C:\Users\Jaydeep Vagadiya\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\node-os-utils\lib\drive.js:62:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2022-10-14 10:34:29.305] [info] [IPC] dockerDaemonStatus
[2022-10-14 10:34:29.319] [info] [IPC] dockerDaemonInstallationCheck
[2022-10-14 10:34:30.505] [info] dockerDaemonInstallationCheckCommand: version 20.10.12
[2022-10-14 10:34:30.822] [error] horizonStatusCommand: error: Command failed: docker exec -t pi-consensus supervisorctl status horizon
Error: No such container: pi-consensus

[2022-10-14 10:34:30.991] [error] dockerContainerStatsCommand: error: Command failed: docker stats pi-consensus --no-stream
Error response from daemon: No such container: pi-consensus

[2022-10-14 10:34:30.996] [error] run: stats: dockerContainerStatsCommand: err: Command failed: docker stats pi-consensus --no-stream
Error response from daemon: No such container: pi-consensus

[2022-10-14 10:34:34.311] [info] [IPC] dockerDaemonStatus
[2022-10-14 10:34:34.352] [info] [IPC] dockerDaemonInstallationCheck
[2022-10-14 10:34:35.229] [info] dockerDaemonInstallationCheckCommand: version 20.10.12

**Comment by CloudBrinkCS** [comment]
I have the same issue. Have you been able to resolve?

**Comment by zhaokai1982** [comment]
Check whether your port output is open and whether the port is open,

**Comment by NeyMR** [comment]
need help with setting up or running into node issues?? https://t.me/+fg3NodtmBpM5ZmJh join us.. 

small but growing operator community helping each other out with issues 🤓👍

**Comment by ipforce20** [comment]
Apparently, you can open all the ports you want, but if there is nothing "listening" then port checkers are going to tell you the port is closed. Google port listener by RJL software. It's free. Run it and open the port you want to check for "open" status.
