### ISSUE TITLE
port listners are not downloading

### ISSUE THREAD

**Issue by slayergithub696** [pi-node/instructions#328]
after docker desktop installation and successfull running i got stuck in open porter routes.After pressing check now no response from three checklist.

**Comment by trefur26** [comment]
Same prob with me

**Comment by Potass** [comment]
Same problem. 'Downloading ports listener' does nothing. Verified on 3 different machines.

**Comment by Potass** [comment]
Resolved by downgrading Docker Desktop app to version 4.18.0.

**Comment by ciprianpavel** [comment]
> Resolved by downgrading Docker Desktop app to version 4.18.0.

worked for me as well

**Comment by cypher7682** [comment]
There's an error from node:

```text
2023-10-16 01:28:35 Can not read port parameters
2023-10-16 01:28:35 Go with default params
2023-10-16 01:28:35 Port 8080
2023-10-16 01:28:35 /usr/src/app/index.js:36
2023-10-16 01:28:35     const port = Number(ports[i].trim()); // remove spaces from the port
2023-10-16 01:28:35                                  ^
2023-10-16 01:28:35 
2023-10-16 01:28:35 TypeError: ports[i].trim is not a function
2023-10-16 01:28:35     at Object.<anonymous> (/usr/src/app/index.js:36:34)
2023-10-16 01:28:35     at Module._compile (internal/modules/cjs/loader.js:778:30)
2023-10-16 01:28:35     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-10-16 01:28:35     at Module.load (internal/modules/cjs/loader.js:653:32)
2023-10-16 01:28:35     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2023-10-16 01:28:35     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2023-10-16 01:28:35     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2023-10-16 01:28:35     at startup (internal/bootstrap/node.js:283:19)
2023-10-16 01:28:35     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by cypher7682** [comment]
It does download the image, but it errors out. I'm just looking for logs. Will report back when I find some

**Comment by cypher7682** [comment]
Okay, so it downloads the image okay, but never seems to start it. I'm running `4.24.2` so it's not docker that's the problem.

**Comment by MrSintay** [comment]
Yes please get in contact with me because somebody stole my computer and all my pie equipment for running the node and pi Network security is an issue here please get in touch with me 310-406-4230Sent from Android deviceOn Oct 15, 2023 5:34 PM, Tim ***@***.***> wrote:
Okay, so it downloads the image okay, but never seems to start it. I'm running 4.24.2 so it's not docker that's the problem.

**Comment by sounak3** [comment]
Downgrading Docker Desktop app to version 4.18.0, worked for me as well.

**Comment by mpekea** [comment]
pls i need help,if click, check now ,no box is ticked

**Comment by mpekea** [comment]
1 am using v4.26.1

**Comment by sounak3** [comment]
Please use version 4.18. That works for me.

**Comment by mpekea** [comment]
thanks,a lot,it worked,

**Comment by mpekea** [comment]
pls help,pi says,"unable to reach the ports in your machine," and last box refuse to mark i mean mycomputer is unable to ping

**Comment by frankycan** [comment]
Thank you guys, with **Docker Desktop 4.18.0** the ports thinkg is solved on **Windows 10 Pro 22H2**.
