### ISSUE TITLE
Docker container refuses to run ( Exited(1) )

### ISSUE THREAD

**Issue by Masgharoth** [pi-node/instructions#340]
Following app instructions docker gets stuck. It seems some open issues hit the same problem.

Silly little docker log for ya

```
2024-02-05 22:30:01 Can not read port parameters
2024-02-05 22:30:01 Go with default params
2024-02-05 22:30:01 Port 8080
2024-02-05 22:30:01 /usr/src/app/index.js:36
2024-02-05 22:30:01     const port = Number(ports[i].trim()); // remove spaces from the port
2024-02-05 22:30:01                                  ^
2024-02-05 22:30:01 
2024-02-05 22:30:01 TypeError: ports[i].trim is not a function
2024-02-05 22:30:01     at Object.<anonymous> (/usr/src/app/index.js:36:34)
2024-02-05 22:30:01     at Module._compile (internal/modules/cjs/loader.js:778:30)
2024-02-05 22:30:01     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2024-02-05 22:30:01     at Module.load (internal/modules/cjs/loader.js:653:32)
2024-02-05 22:30:01     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2024-02-05 22:30:01     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2024-02-05 22:30:01     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2024-02-05 22:30:01     at startup (internal/bootstrap/node.js:283:19)
2024-02-05 22:30:01     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by Yevhen1990** [comment]
Таке сама, що з цим робити?
